import localFont from "next/font/local";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from 'sonner'
import "./globals.css";
import { SignedIn, SignedOut } from "@clerk/nextjs";
import { Suspense } from 'react';
import Loading from "@/components/ui/custom-small/loading";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
  display: 'swap',
  preload: true,
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
  display: 'swap',
  preload: true,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
        <body className="antialiased bg-background text-foreground">
          <Suspense fallback={<Loading />}>
            <SignedIn>
              <SidebarProvider>
                <AppSidebar />
                {/* <SidebarTrigger /> */}
                {children}
              </SidebarProvider>
            </SignedIn>
            <SignedOut>
              {children}
            </SignedOut>
          </Suspense>

          <Toaster richColors position="top-center" expand={false} closeButton />
        </body>
      </html>
    </ClerkProvider>
  );
}

